config/routes.rb
Rails.application.routes.draw do
  # ルートページ
  root "pages#index"

  # クイズのカスタムルート
  get 'quizzes/beginner', to: 'quizzes#beginner', as: 'beginner_quiz'
  get 'quizzes/intermediate', to: 'quizzes#intermediate', as: 'intermediate_quiz'
  get 'quizzes/advanced', to: 'quizzes#advanced', as: 'advanced_quiz'
  get 'quizzes/maniac', to: 'quizzes#maniac', as: 'maniac_quiz'
  get '/correct', to: 'pages#correct', as: 'correct_page'
  get '/incorrect', to: 'pages#incorrect', as: 'incorrect_page'
  get 'quizzes/beginner_result', to: 'quizzes#beginner_result'
  get 'quizzes/intermediate_result', to: 'quizzes#intermediate_result'
  get 'quizzes/advanced_result', to: 'quizzes#advanced_result'
  get 'quizzes/maniac_result', to: 'quizzes#maniac_result'
  get 'quizzes/beginner_result', to: 'quizzes#beginner_result'
  get 'quizzes/intermediate_result', to: 'quizzes#intermediate_result'
  get 'quizzes/advanced_result', to: 'quizzes#advanced_result'
  get 'quizzes/maniac_result', to: 'quizzes#maniac_result'
  get 'quizzes/beginner_result', to: 'quizzes#beginner_result', as: 'beginner_result'
  get 'quizzes/intermediate_result', to: 'quizzes#intermediate_result', as: 'intermediate_result'
  get 'quizzes/advanced_result', to: 'quizzes#advanced_result', as: 'advanced_result'
  get 'quizzes/maniac_result', to: 'quizzes#maniac_result', as: 'maniac_result'
  get 'quizzes/start_astro', to: 'quizzes#start_astro_quiz', as: 'start_astro_quiz'

    # クイズの回答を処理するルート
  post 'quizzes/astro_answers', to: 'quizzes#astro_answers', as: 'astro_quiz_answers'
    # クイズの結果を表示するルート
  get 'quizzes/:id/astro_results', to: 'quizzes#astro_results', as: 'astro_results_quiz'

  post 'quizzes/intermediate/answer', to: 'quizzes#answer_intermediate', as: 'answer_intermediate_quiz'

  


  # クイズに関連するルート
  resources :quizzes, only: [:index] do
    member do
      get 'results'
    end

    resources :questions, only: [:show] do
      post 'answer', on: :member
    end
  end
    # 質問に関連するルート
    
     

  # ... 他のルートがあればここに追加 ...
end

app/controllers/quizzes_controller.rb
# app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
 include GoogleApiConcern

  def astro_results
    @quiz = Quiz.find(params[:id])
    @answers = session[:answers] || {}   
  end

  def start_astro_quiz
  @quiz = Quiz.where(level: 'astro').first # 例として 'astro' レベルを仮定
    if @quiz && @quiz.questions.any?
      render 'start_astro_quiz', locals: { quiz: @quiz }
      else
        redirect_to root_path, alert: "アストロ君のクイズが利用可能ではありません。ごめんなさい・・・"
      end
    end
   
    def beginner
       @quiz = Quiz.where(level: 'beginner').first
      if @quiz && @quiz.questions.any?
        render 'beginner', locals: { quiz: @quiz }
      else
        redirect_to root_path, alert: "利用可能な初級者向けのクイズがありません。ごめんなさい・・・"
       end
    end
    
    def intermediate
      @quiz = Quiz.where(level: 'intermediate').first
      if @quiz && @quiz.questions.any?
         @question = @quiz.questions.first  # 最初の質問をセット
         render 'intermediate', locals: { quiz: @quiz }
      else
         redirect_to root_path, alert: "利用可能な種類当てクイズがありません。ごめんなさい・・・"
       end
    end
    
    def advanced
      @quiz = Quiz.where(level: 'advanced').first
      if @quiz && @quiz.questions.any?
        render 'advanced', locals: { quiz: @quiz }
      else
        redirect_to root_path, alert: "利用可能な中級者向けのクイズがありません。ごめんなさい・・・"
      end
    end
    
    def maniac
      @quiz = Quiz.where(level: 'maniac').first
       if @quiz && @quiz.questions.any?
         render 'maniac', locals: { quiz: @quiz }
      else
        redirect_to root_path, alert: "利用可能なマニアックなクイズがありません。ごめんなさい・・・"
      end
    end

    def results 
      @answers = session[:answers] || {}
      @quiz = Quiz.find(params[:id])

      @correct_answers_count = 0
      @quiz.questions.each do |question|
        if @quiz.level == 'intermediate'
          # 中級レベルの場合、テキスト回答をチェック

          # `@answers[question.id.to_s]` から 'answer' キーの値を取得します。
          # `rescue nil` を使用しているため、`@answers[question.id.to_s]` が nil であるか、
          # 'answer' キーが存在しない場合には nil を返します。この方法は意図しないエラーも
          # 捕捉してしまうため、使用する際には注意が必要です。また、例外処理は比較的コストが高いため、
          # パフォーマンスに影響を与える可能性があります。
          user_answer = @answers[question.id.to_s]['answer'] rescue nil
          correct_answers = question.answer.split(',').map(&:downcase)
          is_correct = correct_answers.include?(user_answer&.downcase)
          @correct_answers_count += 1 if is_correct
        else
          # その他のレベルの場合、選択した選択肢から回答をチェック
          user_answer_id = @answers[question.id.to_s]['choice_id'] rescue nil
          correct_choice = question.choices.find_by(correct: true)
          @correct_answers_count += 1 if correct_choice && user_answer_id == correct_choice.id
        end
      end
    end
    
     def beginner_result
       # 必要なデータを取得
     end
           
     def intermediate_result
        # 必要なデータを取得
     end
          
     def advanced_result
        # 必要なデータを取得
     end
          
     def maniac_result
        # 必要なデータを取得
     end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_astro_level_results.html.erb
<% if @quiz.level == 'astro' %>
  <h3 class="text-center text-white mb-3">アストロ君を探してね！！！</h3>
  <p class="text-warning text-center">みんな見つけられたかな？？  プレイしてくれて、ありがとう！！</p>
  <%= image_tag "image.png", alt: "残念賞！", class: 'img-fluid mx-auto d-block mb-4' %>
  <% @quiz.questions.each do |question| %>
    <div class="row mb-5 bg-dark text-white">
      <div class="col-md-6">
        <strong class="text-white font-weight-bold">問題:</strong> <%= question.content %>
      </div>
      <div class="col-md-6 text-right">
        <strong class="text-white font-weight-bold">正解座標:</strong>
        X1: <%= question.correct_x1 %>, Y1: <%= question.correct_y1 %>,
        X2: <%= question.correct_x2 %>, Y2: <%= question.correct_y2 %>
      </div>
    </div>
  <% end %>
  <%= link_to "最初のページに戻ります！", root_path, class: "btn btn-primary" %>
<% end %>

app/views/quizzes/_regular_quiz_results.html.erb
 <% @quiz.questions.each do |question| %>
  <div class="row mb-3 bg-dark text-white "> <!-- 背景を暗色にして文字を白色にする -->
    <div class="col-md-4">
      <strong class="text-white font-weight-bold">問題:</strong> <%= question.content %>
    </div>
    <div class="col-md-4">
      <strong class="text-white font-weight-bold">あなたの回答:</strong> <%= @answers[question.id.to_s] ? Choice.find_by(id: @answers[question.id.to_s])&.content : "回答がありません" %>
    </div>
    <div class="col-md-4">
      <strong class="text-white font-weight-bold">正解:</strong> <%= question.choices.find_by(correct: true)&.content %>
    </div>
  </div>
<% end %>

app/views/quizzes/_score.html.erb
<div id="score">
  <p>Your score is: <%= score %></p>
</div>

app/views/quizzes/advanced.html.erb
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
      <h1 class="text-danger">中級者向けクイズ</h1>
      <p>爬虫類の専門知識を試す時です！準備はいいですか？</p>
      <%= link_to 'クイズを開始する', quiz_question_path(@quiz, @quiz.questions.first), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/quizzes/advanced_result.html.erb
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
    <h2>アミメミズベトカゲ</h2>
    <%= image_tag "37520.jpg",class: 'img-fluid d-block mx-auto', style: 'width: 90%; height: auto;' %>
  </div>
  </div>
</div>

app/views/quizzes/astro_results.html.erb
<!-- app/views/quizzes/results.html.erb -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 bg-dark text-white p-3 rounded">
      <h2 class="text-center">クイズ結果</h2>
      <div class="text-center my-4">
        <% app_name = "辰年なので、爬虫類に興味を持ちましょう！！" %>
        <% app_url = "https://reptile-recommend-df15caef12da.herokuapp.com/" %>
        <% tweet_text = "#{app_name}\nあなたも、アストロ君を探してみませんか？？？\n#{app_url}" %>
        <%= link_to "結果をTwitterで共有する", "https://twitter.com/intent/tweet?text=#{CGI.escape(tweet_text)}", target: "_blank", class: "btn btn-primary mb-4" %> <!-- mb-4 を追加 -->
        <% if @quiz.level == 'astro' %>
          <%= render 'astro_level_results', quiz: @quiz, answers: @answers %>
        <% else %>
          <!-- 通常のクイズ結果表示 -->
          <%= render 'regular_quiz_results', quiz: @quiz, answers: @answers %>
        <% end %>
      </div>
    </div>
  </div>
</div>

  

app/views/quizzes/beginner.html.erb
<!-- app/views/quizzes/beginner.html.erb -->
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
      <h1 class="text-danger">初心者向けクイズ</h1>
      <p>とりあえず、爬虫類って何だろう？という感じの人向けです。</p>
      <%= link_to 'クイズを開始する', quiz_question_path(@quiz, @quiz.questions.first), class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/quizzes/beginner_result.html.erb
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
    <h2>アミメミズベトカゲ</h2>
    <%= image_tag "image.jpg",class: 'img-fluid d-block mx-auto', style: 'width: 90%; height: auto;' %>
    </div>
  </div>
</div>

app/views/quizzes/intermediate.html.erb
<!-- app/views/quizzes/intermediate.html.erb -->
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
      <h1 class="text-danger">この爬虫類は何でしょう？？</h1>
      <p>ここでは、爬虫類の名前を当てるクイズです！！</p>
      <p> フォームに、カタカナで直接記載してね！！</p>
      <p>＊ヒント＊   わからなかったら、画像の名前を注目してね！！</p>
      <%= link_to 'クイズを開始する', '#', id: 'startQuizBtn', class: 'btn btn-primary' %>
    </div>
  </div>
</div>

<div id="customModal" class="custom-modal" style="display:none;">
  <div class="custom-modal-content">
    <span class="custom-modal-close">&times;</span>
    <p>爬虫類の写真が出るますが進みますか？？</p>
    <!-- リンクやボタンをここに追加 -->
    <%= link_to 'はい',quiz_question_path(@quiz, @quiz.questions.first), class: 'btn btn-primary' %>
    <%= link_to 'いいえ', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

<!-- 既存のHTMLコード -->
<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function () {
    var modal = document.getElementById("customModal");
    var startQuizBtn = document.getElementById("startQuizBtn"); // クイズ開始ボタン
    var span = document.getElementsByClassName("custom-modal-close")[0];

    startQuizBtn.onclick = function() {
      modal.style.display = "block";
      return false; // デフォルトの動作を防ぐ
    }

    span.onclick = function() {
      modal.style.display = "none";
    }

    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
  });
</script>

app/views/quizzes/intermediate_result.html.erb
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
    <h2>アミメミズベトカゲが孵化してた！！</h2>
   <%= image_tag"アミメ生まれてた.jpg", class: 'img-fluid d-block mx-auto', style: 'width: 90%; height: auto;' %>
<!-- ここに追加の内容やデータを表示するコードを追加 -->
  </div>
  </div>
</div>

app/views/quizzes/maniac.html.erb
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
      <h1 class="text-danger">マニアック！！</h1>
      <p>多分、初見だと満点きついと思います！</p>
      <%= link_to 'クイズを開始する', '#', id: 'startQuizBtn', class: 'btn btn-primary' %>
    </div>
  </div>
</div>
<div id="customModal" class="custom-modal" style="display:none;">
  <div class="custom-modal-content">
    <span class="custom-modal-close">&times;</span>
    <p>トカゲの写真も出るよ！！準備はいい？</p>
    <%= link_to 'はい', quiz_question_path(@quiz, @quiz.questions.first), class: 'btn btn-primary' %>
    <%= link_to 'いいえ', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

<!-- 既存のHTMLコード -->
<script type="text/javascript">
document.addEventListener('DOMContentLoaded', function () {
  var modal = document.getElementById("customModal");
  var startQuizBtn = document.getElementById("startQuizBtn");
  var span = document.getElementsByClassName("custom-modal-close")[0];
  var closeBtn = document.getElementById("customModalClose");

  startQuizBtn.onclick = function() {
    modal.style.display = "block";
    return false; // デフォルトの動作を防ぐ
  }

  span.onclick = function() {
    modal.style.display = "none";
  }

  closeBtn.onclick = function() {
    modal.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }
});
</script>

app/views/quizzes/maniac_result.html.erb
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
    <h2>ミミナシオオトカゲ</h2>
    <%= image_tag "37515.jpg" ,class: 'img-fluid d-block mx-auto', style: 'width: 90%; height: auto;' %>
  </div>
  </div>
</div>

app/views/quizzes/results.html.erb
<!-- app/views/quizzes/results.html.erb -->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8 bg-dark text-white p-3 rounded"> <!-- 背景とテキストの色を設定 -->
      <h2 class="text-center">クイズ結果</h2>
      <p class="text-center">あなたの正解数: <%= @correct_answers_count %> / <%= @quiz.questions.count %></p>
      <div class="text-center my-4">
      <% app_name = "辰年なので、爬虫類に興味を持ちましょう！！" %>
      <% app_url = "https://reptile-recommend-df15caef12da.herokuapp.com/" %>
      <% tweet_text = "#{app_name}\n私のクイズのスコア（#{I18n.t('quiz_levels.' + @quiz.level)}）は#{@correct_answers_count} / #{@quiz.questions.count}でした！\n#{app_url}" %>
      <%= link_to "結果をTwitterで共有する", "https://twitter.com/intent/tweet?text=#{CGI.escape(tweet_text)}", target: "_blank", class: "btn btn-primary" %>

      <% score_percentage = (@correct_answers_count.to_f / @quiz.questions.count) * 100 %>

      <% if @correct_answers_count == @quiz.questions.count %>
        <p class="text-warning text-center">おめでとうございます！満点です！自慢しましょう！！トカゲの写真見ます？？！！</p>
        <% case @quiz.level %>
        <% when 'beginner' %>
          <%= link_to "トカゲの写真", beginner_result_path, class: 'text-warning' %>
        <% when 'intermediate' %>
          <%= link_to "トカゲの写真", intermediate_result_path, class: 'text-warning' %>
        <% when 'advanced' %>
          <%= link_to "トカゲの写真", advanced_result_path, class: 'text-warning' %>
        <% when 'maniac' %>
          <%= link_to "トカゲの写真", maniac_result_path, class: 'text-warning' %>
        <% end %>
      <% elsif score_percentage >= 80 %>
        <p class="text-warning text-center">あなたは爬虫類の知識が豊富ですね！とりあえず、自慢しましょう！！</p>
      <% else score_percentage < 50 %>
     <p class="text-warning text-center">ナイスファイト！！もう少しで専門家になれるよ！！残念賞も見てね！</p>
      <%= link_to "残念賞！#{@random_image_name}(イラストだよ）", @random_image_url, target: "_blank" %>
      <% end %>
      
   <% @quiz.questions.each do |question| %>
  <div class="row mb-3 bg-dark text-white "> <!-- 背景を暗色にして文字を白色にする -->
    <div class="col-md-4">
      <strong class="text-white font-weight-bold">問題:</strong> <%= question.content %>
    </div>
    <div class="col-md-4">
      <% if @quiz.level == 'intermediate' %>
        <!-- 中級レベルの場合、セッションからユーザーのテキスト回答を表示 -->
       <strong class="text-white font-weight-bold">あなたの回答:</strong> <%= @answers[question.id.to_s] ? @answers[question.id.to_s]['answer'] : "回答がありません" %>
      <% else %>
        <!-- それ以外のレベルの場合、選択した選択肢から回答を表示 -->
        <strong class="text-white font-weight-bold">あなたの回答:</strong> <%= @answers[question.id.to_s]&.dig('choice_id') ? Choice.find_by(id: @answers[question.id.to_s]['choice_id'])&.content : "回答がありません" %>
      <% end %>
    </div>
    <div class="col-md-4">
      <% if @quiz.level == 'intermediate' %>
        <!-- 中級レベルの場合、質問の`answer`属性から正解を表示 -->
        <strong class="text-white font-weight-bold">正解:</strong> <%= question.answer %>
      <% else %>
        <!-- それ以外のレベルの場合、正しい選択肢から正解を表示 -->
        <strong class="text-white font-weight-bold">正解:</strong> <%= question.choices.find_by(correct: true)&.content %>
      <% end %>
    </div>
  </div>
<% end %>
 <%= link_to "最初のページに戻ります！", root_path, class: "btn btn-primary" %>

app/views/quizzes/start_astro_quiz.html.erb
<!-- app/views/quizzes/start_astro_quiz.html.erb -->
<div class="container mt-5 mb-3">
  <div class="row justify-content-center"> <!-- 中央に配置 -->
    <div class="col-12 col-md-8 bg-dark text-white p-3 rounded text-center"> <!-- 背景とテキストの色を設定し、中央に配置 -->
     <h1 class="text-danger mb-3">アストロ君を探してね！！！</h1>
     <p class="mb-3">この子が隠れてるので探してね！！！！</p>
     <%= image_tag("asutoro.jpg", alt: "Beginner Image", class: "img-fluid") %>
     <%= link_to 'クイズを開始する', quiz_question_path(@quiz, @quiz.questions.first), class: 'btn btn-primary mt-3 mb-3' %>
    </div>
  </div>
</div> 